name: CI


on:
    push:
        branches:
            -main

    pull_request:
        branches:
            -main

jobs:

    typecheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-nodes@v3
              with:
                node-version: 16.x
                cache: npm

            - name: Install
              run: npm install

            - name: Typecheck
              run: npm run typecheck
            
