name: Copy To Branches
on:
    workflow_dispatch
jobs:
    Copy-to-branches:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fecth-depth: 0
            - name: Copy To Branches Action
              uses: planetofthewed/copy-to-branches@v1.2
              env:
                key: main